sudo: false

language: node_js
node_js:
  - '10.16'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo 'export const ENV = {parseAppId:"",parseJavascriptKey:"",parseServerUrl:"",parseMasterKey:"" }' > src/app/app.constant.ts
install:
  - npm install -g codecov

script:
  - npm ci --no-optional
  - npm run test-coverage
  - npm run website:build