sudo: false

language: node_js
node_js:
  - '10.16'

install:
  - npm install -g codecov

script:
  - npm ci --no-optional
  - touch src/app/app.constant.ts
  - npm run test && codecov
  - npm run build