sudo: false

language: node_js
node_js:
  - '10.16'
before_install:
  - echo 'export const ENV = { }' > src/app/app.constant.ts
install:
  - npm install -g codecov

script:
  - npm ci --no-optional
  
  - npm run test && codecov
  - npm run build